services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nextjs-rewind
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - APP_URL=https://rewindproduction.ru